[package]
name = "steamworks"
version = "0.7.0"
authors = ["Thinkofname"]
description = "Provides rust friendly bindings to the steamworks sdk"
license = "MIT / Apache-2.0"
repository = "https://github.com/Thinkofname/steamworks-rs"
documentation = "https://docs.rs/steamworks"
keywords = ["steam", "gamedev"]
categories = ["games"]
edition = "2018"

[package.metadata.docs.rs]
features = [ "docs-only" ]

[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = ["steamworks-sys/docs-only"]

[workspace]
members = [
    "./steamworks-sys"
]

[dependencies]
steamworks-sys = {path = "./steamworks-sys", version = "0.7.0"}
thiserror = "1.0.24"
bitflags = "1.2.1"
lazy_static = "1.4.0"
serde = { version = "1.0.123", features = ["derive"], optional = true }

[dev-dependencies]
serial_test = "0.5.1"
serial_test_derive = "0.5.1"
